services:
 loe-parser:
    platform: linux/amd64
    container_name: loe-parser
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - loe-data:/app
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - TZ=Europe/Kyiv
      # - DEBUG=puppeteer:*
volumes:
  loe-data: