services:
  loe-parser:
    platform: linux/amd64
    container_name: loe-parser
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - loe-data:/app
    entrypoint: ["/app/parse-image"]
    environment:
      - TZ=Europe/Kyiv
    # restart: on-failure
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 10m # Run every 10 minutes
    #     max_attempts: 0
volumes:
  loe-data: